### ISSUE TITLE
Attribute autocompletion does not work for components created via svelte-kit package

### ISSUE THREAD

**Issue by MarvinJWendt** [tomblachut/svelte-intellij#270] opened 2022-01-12 01:59 UTC
Hi, the attribute autocomplete is not working for imported components that are written in TypeScript.

Here is a screenshot of a component that was created locally:
![image](https://user-images.githubusercontent.com/31022056/149050135-6a6c1274-54bb-4297-81d0-d9b2591ebe2c.png)

Here a screenshot of the same component (copy-paste code) from an external library (created via svelte-kit package):

![image](https://user-images.githubusercontent.com/31022056/149050192-c64ce3ce-8dda-4caa-b92c-76ef2d644dd0.png)

**Imports**

```typescript
import {Button, ContainerCenterOnPage, Heading} from "@marvinjwendt/svelte-component-kit"; // Autocomplete does not work
import TestComp from "../components/TestComp.svelte"; // Autocomplete does work
```

**Comment by tomblachut** [comment] 2022-01-12 17:50
Hi, duplicate of #206

**Closed by tomblachut** 2022-01-12 17:50 UTC
