### ISSUE TITLE
Support for lang="ts" / TypeScript

### ISSUE THREAD

**Issue by An-Cu** [tomblachut/svelte-intellij#32] opened 2019-07-18 08:44 UTC
I want to use svelte in typescript by using svelte-ts-preprocess preprocess
It would be great to add support for <script lang="ts"></script>.

Let me know if I can help you.

**Comment by tomblachut** [comment] 2019-07-18 23:12
TS support could be more complicated that it seems. Currently I decided to hardcode JS because there are different parts required to coordinate. `SvelteCodeMultiHostInjector` uses some stringly typed black magic to enable JS support inside interpolations. JS inside script tag is injected by underlying HTML language support native to IDE. There are also props which are unsupported right now.

**Comment by nitro52** [comment] 2019-10-31 07:09
typescript lang support can be partially supported using the svelte-preprocessor. How ever there is a current bug in windows machines that causes a bunch of errors. It seems like this will be fixed soon. 

I setup a webpack template using this. https://github.com/nitro52/svelte-typescript-sass-template

**Comment by JakubKoralewski** [comment] 2019-12-22 12:34
I'm new to the Java/Kotlin/IntelliJ-plugin-ecosystem, but I'd love to help any way I can as well.

**Comment by sethlivingston** [comment] 2020-03-05 14:39
Would love to see this generalized to lang="<any lang IDE supports>" if possible. Also happy to help.

**Comment by tomblachut** [comment] 2020-03-05 14:57
@sethlivingston IntelliJ doesn't work that way. You need to enable support for each and every language manually, implement coding assistance and painfully debug many integration bugs.

TS is the official future of Svelte so it will be supported eventually.

**Comment by sethlivingston** [comment] 2020-03-05 15:08
Understood. Thanks for the clarification!

**Comment by syabro** [comment] 2020-06-03 08:37
https://github.com/sveltejs/svelte/issues/4518#issuecomment-637811378

`typescript` is kinda supported now
@tomblachut any luck we can have it in IDEA?

**Comment by daarxwalker** [comment] 2020-06-17 10:33
@tomblachut 
Hi,
btw. great plugin!
Status about TS support? Svelte supports TS with no problem, but can't work with it and I rlly don't want use VSC.
It could be great, if I cant finally develop with TS support!
Have a nice day!

**Comment by Dan1ve** [comment] 2020-07-18 12:46
This would be so awesome.

Right now, I'm forced to switch between VS Code (which supports Typescript nicely, but doesn't really work for imports and Svelte-specific things) and IntelliJ (where -thanks for this great plugin- everything works _perfectly_, except the `lang="typescript"` support.

Please let me know if I can help!

**Comment by tomblachut** [comment] 2020-07-28 16:43
It is great that there's official Svelte Language Server, it will definitely help. On the other side I just don't know how to integrate that 😅 

I feel your pain given that I personally love TS.

@syabro @Dan1ve is it `lang="typescript"` or `lang="ts"`?  https://svelte.dev/blog/svelte-and-typescript says `ts`


Rough roadmap: 

1. Another rewrite related to #100 - currently it's throwing IDE errors for HTML edge cases that are older than me. I didn't find a way to break that MR into smaller parts unfortunately. I burned out like 3 times already on that.
2. Add regression tests. I've promised @daarxwalker some backlog for that an eternity ago. I still don't have one but right now i'm on a time off from work so hopefully will complete point 1. and then write that backlog.
3a. Extend parsers so they understand lang attribute.
3b. Integrate with LSP.

**Comment by r00t3g** [comment] 2020-07-28 17:07
@tomblachut there is a plugin bringing LSP support into IntelliJ IDEs: https://github.com/gtache/intellij-lsp , however, AFAIK, it does not introduce any syntax highlighting features, niether any code navigation. Neverthelss, it might be helpful looking through it code, dunno

**Comment by tomblachut** [comment] 2020-07-28 17:15
@r00t3g there are even two, I imagine that plugin shows code for IPC between IntelliJ and node, and ofc spawning and killing that node process. Second part is I guess loading correct svelte-language-server (from package.json?) into that node instance. Folks from Svelte already implemented code navigation, right? (I didn't had a chance to checkout this new plugin)

There also classes built into IJ:

![image](https://user-images.githubusercontent.com/615013/88698446-59832f80-d106-11ea-8e43-54c79120c6c2.png)

Anyway probably the best way is to rip things from Vue plugin as I've always done with other code. They recently reworked that so should be best-in-class

**Comment by tomblachut** [comment] 2020-07-28 17:25
I'm gonna link LSP issue #98 here

**Comment by Dan1ve** [comment] 2020-07-29 06:57
> It is great that there's official Svelte Language Server, it will definitely help. On the other side I just don't know how to integrate that 😅
> 
> I feel your pain given that I personally love TS.
> 
> @syabro @Dan1ve is it `lang="typescript"` or `lang="ts"`? https://svelte.dev/blog/svelte-and-typescript says `ts`
> 
> Rough roadmap:
> 
>     1. Another rewrite related to #100 - currently it's throwing IDE errors for HTML edge cases that are older than me. I didn't find a way to break that MR into smaller parts unfortunately. I burned out like 3 times already on that.
> 
>     2. Add regression tests. I've promised @daarxwalker some backlog for that an eternity ago. I still don't have one but right now i'm on a time off from work so hopefully will complete point 1. and then write that backlog.
> 
>     3. Enable TS
>        3a. Extend parsers so they understand lang attribute.
>        3b. Integrate with LSP.

@tomblachut it appears that both `typescript` and `ts` work in the new official feature and VS Code.

**Comment by anstarovoyt** [comment] 2020-07-29 08:39
@tomblachut my thoughts:

1. We still have to add parsing support for typescript on the IDE side because without proper AST almost all smart IDE features don't work (the main issue is that LSP API is very limited and it cannot cover all IDE features).
2. Yes, we already use typescript service (it isn't lsp but very close) for code insights in vue and ts files. We use it for completion and error highlightings. 
3. The simplest example of using "server <-> IDE" communication is the tslint plugin: https://github.com/JetBrains/intellij-plugins/tree/master/tslint

So from my point of view roadmap can look like:
1. Add ts syntax support on the IDE side
2. Introduce LSP integration over regular ts support similar to vue / ts

**Comment by anstarovoyt** [comment] 2020-07-29 08:41
@tomblachut also I am ready to implement some part of the support, but we need some decision about  https://github.com/tomblachut/svelte-intellij/pull/100 :)

**Comment by tomblachut** [comment] 2020-07-29 10:48
@anstarovoyt  thanks I'm gonna go through your links later,

so the first thing to do would be to fork SvelteJSLanguage and SvelteJSParserDefinition, reactive labels will complicate that a bit.

**Comment by unlocomqx** [comment] 2020-08-03 13:29
I did a simple comparison with the vue plugin, here you can see that the embedded content type is not the same
![2020-08-03_14-25](https://user-images.githubusercontent.com/793712/89187665-7f408680-d595-11ea-956e-d10bc97ff94e.png)

In vue, you get better completion and highlighting
![image](https://user-images.githubusercontent.com/793712/89187736-94b5b080-d595-11ea-85a1-bccdf2666690.png)

Svelte
![image](https://user-images.githubusercontent.com/793712/89187867-c0389b00-d595-11ea-9271-879a514a969f.png)

**Comment by tomblachut** [comment] 2020-08-03 21:15
Can someone verify whether `as` casts are supported in each block?

my favourite svelte JS code (name shadowing but totally valid code):
```
{#each as as as (as)}
```

would become
```
{#each as as string[] as as as string (as)}
```

**Comment by anstarovoyt** [comment] 2020-08-18 10:57
@tomblachut do you plan to implement it in the nearest future? if not, I can try to provide an implementation sketch this week.

**Comment by tomblachut** [comment] 2020-08-18 11:13
@anstarovoyt I wanted to tackle reactivity first, so I think it's okay that you work on TS sketch. The only concern is whether both features will work together

**Comment by anstarovoyt** [comment] 2020-08-18 11:16
it is the reason why I call it "scratch". So we can take a look and discuss possible solutions to make it work with reactivity.

**Comment by tomblachut** [comment] 2020-08-18 11:23
Ok, go ahead, thanks

**Comment by dummdidumm** [comment] 2020-08-19 06:25
> Can someone verify whether `as` casts are supported in each block?

Right now only JavaScript is supported in the template, see this issue for more info https://github.com/sveltejs/svelte/issues/4701

**Comment by tomblachut** [comment] 2020-10-19 13:18
Hi everyone! You can grab version 0.15.0 from within your IDE and use TS now.

https://plugins.jetbrains.com/plugin/12375-svelte/versions/stable/99919

Feel free to open additional issues around improvements.

**Closed by tomblachut** 2020-10-19 13:18 UTC
Labels: Svelte core, impact: major

**Comment by syabro** [comment] 2020-10-19 13:23
Doesn't work :(

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/29029/96456500-3e1c5200-1227-11eb-8497-4f629d946c26.png">

<img width="388" alt="image" src="https://user-images.githubusercontent.com/29029/96456510-41174280-1227-11eb-95bc-a5ae67cd49c2.png">

<img width="821" alt="image" src="https://user-images.githubusercontent.com/29029/96456558-4d9b9b00-1227-11eb-8084-d181f845dcec.png">

**Comment by tomblachut** [comment] 2020-10-19 13:25
@syabro This issue is about lang="ts", type checking of props will come later. Cheers!

**Comment by syabro** [comment] 2020-10-19 13:37
Oh, sorry.
@tomblachut should I open an issue about it?

**Comment by tomblachut** [comment] 2020-10-19 14:01
@syabro Don't worry I could've communicated it more clearly. Anyway it's better to release small increments more often if possible so here you go 😁 

Depends what you want to achieve/discuss really. There are two different issues already connected to your image.

#98 tackles LSP and I have no ETA on that, it will bring everything (I think) folks at [sveltejs/language-tools](https://github.com/sveltejs/language-tools) are busy supporting (@dummdidumm mostly, thank you!)

#11 is an old but still relevant issue basically about improvements to html attributes - I just updated the title and description to better reflect current status, I want to do it next, before moving codebase to 2020.3. Type checking using builtin IDE engine could come after that one.

Anyway feel free to open issues if you like, that's what they are here for.
