### ISSUE TITLE
Wrong attribute value when using a reactive variable $:

### ISSUE THREAD

**Issue by AnthoniG** [tomblachut/svelte-intellij#260] opened 2021-12-18 05:48 UTC
`<button disabled={disabled} type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">Sign in</button>`

The above html fragment highlights the disabled when I am using a reactive statement.
It works perfectly in the browser, but in Webstorm it is highlighting these and it's very frustrating because I need to keep checking if missed something.

Not sure if can fix this, or if I have to block the intention.

Anyone any ideas ?

----
edit
----
Just found this on Webstorm blog 

[Disable inspection "wrong attribute value"](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360008267020-Disable-inspection-wrong-attribute-value-)

It seems, as Elena Pogorelova says, that it is a low level check and thus it can not be disabled.

Does this mean your plugin as well ?

**Comment by tomblachut** [comment] 2021-12-21 21:35
> Does this mean your plugin as well?

The linked problem is connected partially. We can hide the warning for computed/dynamic expressions on Svelte plugin side with update.

The actual check is indeed low level and cannot be configured in the settings, that's what Elena meant.

Actually, this is a duplicate of #260

**Closed by tomblachut** 2021-12-21 21:35 UTC
