### ISSUE TITLE
Error in intellij when using keyed each with trailing space

### ISSUE THREAD

**Issue by Dudek-AMS** [tomblachut/svelte-intellij#281] opened 2022-03-28 10:05 UTC
```javascript
{#each $RequestStore.RequestUsers as request (request.__uuid) }
```

the space after (request.__uuid) displays a error in intelli (unexpected token).

**Comment by tomblachut** [comment] 2022-03-28 17:37
Duplicate of #273

**Closed by tomblachut** 2022-03-28 17:37 UTC
