### ISSUE TITLE
Handle attributes

### ISSUE THREAD

**Issue by bravecow** [tomblachut/svelte-intellij#59] opened 2019-09-03 14:15 UTC
1. Attributes are highlighted as "not allowed":

![image](https://user-images.githubusercontent.com/988471/64180627-c85ff600-ce6d-11e9-8b17-30b1aefd0a53.png)

Yes, we can add them to custom attributes in config, but maybe it is possible to automatically add them [(`on:*`, `bind:*`, ... )](https://svelte.dev/docs#Element_directives) in `.svelte` files.

2. Make "Go to declaration" possible:

![image](https://user-images.githubusercontent.com/988471/64180862-2d1b5080-ce6e-11e9-974c-12a480d6767b.png)

Thanks! 👍

**Comment by tomblachut** [comment] 2019-09-03 14:27
Duplicate of #2 & #11. Will be done before 1.0

**Closed by tomblachut** 2019-09-03 14:27 UTC
