### ISSUE TITLE
Autocomplete doesn't work for non-svelte files.

### ISSUE THREAD

**Issue by Shaunwild97** [tomblachut/svelte-intellij#275] opened 2022-03-08 20:12 UTC
I'm not exactly sure what causes autocomplete not to work, but I'm guessing it's because of references to .ts files instead of .svelte files.

You would expect all of the props mentioned in `Table.d.ts` file to show on the autocomplete menu.

It should also take into account the `extends svelte.JSX.HTMLAttributes<HTMLElementTagNameMap['table']` which means we get all of the lovely `table html` autocompletions

![image](https://user-images.githubusercontent.com/10476581/157316808-dc19a522-efaa-49f7-af88-4e7cfa7b0d78.png)

![image](https://user-images.githubusercontent.com/10476581/157316984-a926f6d2-2f23-462e-83f9-eab65273dda8.png)

**Comment by tomblachut** [comment] 2022-03-09 13:03
Duplicate of #206, and probably some others

**Closed by tomblachut** 2022-03-09 13:03 UTC
