### ISSUE TITLE
No syntax highlighting of expressions inside title tag

### ISSUE THREAD

**Issue by diontron** [tomblachut/svelte-intellij#272] opened 2022-02-20 09:21 UTC
First off, thank you so much for this plugin.

I am not getting syntax highlighting / completion inside `svelte:head` eg:

```
<script>
    export let app
</script>

<svelte:head>
    <title>Hello | {app.name}</title>
</svelte:head>

<h1 class="text-3xl font-bold underline">
    Hello world! {app.name}
</h1>
```

I get it inside the `h1`, but not inside `svelte:head`.

**Comment by tomblachut** [comment] 2022-02-22 12:42
Duplicate of #210

**Closed by tomblachut** 2022-02-22 12:42 UTC
Labels: triage: duplicate
