### ISSUE TITLE
improvement: highlighting for sass, less, stylus

### ISSUE THREAD

**Issue by 890f2151c2be69c51db72017546d00fd** [tomblachut/svelte-intellij#29] opened 2019-07-11 13:43 UTC
it would be nice improve highlighting for sass, less, stylus

![image](https://user-images.githubusercontent.com/1290687/61055818-93e23780-a3f2-11e9-9618-d658d2c64333.png)

**Comment by unlocomqx** [comment] 2019-07-29 09:37
@tomblachut 
I was able to implement this in https://github.com/unlocomqx/svelte-intellij/tree/highlight
but I don't like this bit
https://github.com/unlocomqx/svelte-intellij/blob/e4b275f2640378f142850b0bbcca2cd2c17eab85/src/main/resources/META-INF/plugin.xml#L76
 because it affects non-svelte files as well, if you find a better way to override `HtmlLexer`, please let me know

![image](https://user-images.githubusercontent.com/793712/62037559-e93c8800-b1eb-11e9-9b84-caa596e13945.png)

I copied it from VueJS plugin

**Comment by rezadru** [comment] 2019-08-09 14:25
Duplicate of #17 ?

**Comment by tomblachut** [comment] 2019-08-14 20:13
@Gameghostify, yes partially, but I'd say it's another way around because #29 includes in its scope #17. I'll leave both of them for now.

**Comment by timEulitz** [comment] 2019-10-02 12:21
Hey, I just wanted to add PostCSS to the mix, I assume that most people who care about this issue use the following package or a similar one:

https://www.npmjs.com/package/svelte-preprocess

Given that it supports PostCSS, SCSS, Less, Stylus, Coffeescript, TypeScript and Pug, I guess that would be the complete list that should be supported by the IntelliJ plugin.

**Comment by marcus-sa** [comment] 2019-10-09 11:56
What about TypeScript highlighting?
It might not be officially supported, but I'm using it with Svelte.
https://github.com/avantci/rules_svelte

**Closed** 2019-11-12 23:55 UTC
Labels: help wanted
