### ISSUE TITLE
Add support for @const

### ISSUE THREAD

**Issue by catapop84** [tomblachut/svelte-intellij#297] opened 2022-07-22 13:40 UTC
https://svelte.dev/docs#template-syntax-const

```
<script>
	export let boxes;
</script>

{#each boxes as box}
	{@const area = box.width * box.height}
	{box.width} * {box.height} = {area}
{/each}
```

in this example I receive this error: `Expected html or debug`

I'm using plugin version 0.22.1 with webstorm 2022.1.4

**Comment by dominikg** [comment] 2022-07-23 12:03
duplicate of #268

**Closed** 2023-02-22 22:08 UTC
