### ISSUE TITLE
CSS functions in inline CSS don't work with Svelte string templates

### ISSUE THREAD

**Issue by TheOnlyTails** [tomblachut/svelte-intellij#244] opened 2021-08-19 18:33 UTC
I have this attribute in my component:
```svelte
<div style="transform: translateY({Math.floor(scrollY / -10)}px)">
```
However, this error appears when inserting the braces in the function: ![image](https://user-images.githubusercontent.com/65342367/130124772-711eb974-d1c4-43a1-9333-f121aaf917bf.png)

**Comment by tomblachut** [comment] 2021-08-20 11:19
Duplicate of #80

**Closed by tomblachut** 2021-08-20 11:19 UTC
