### ISSUE TITLE
Inline CSS broken after first ´statement which references a variable

### ISSUE THREAD

**Issue by DavidBeh** [tomblachut/svelte-intellij#279] opened 2022-03-19 22:27 UTC
![image](https://user-images.githubusercontent.com/67109172/159140253-837e198e-9806-4868-9c1f-5fc77039c55d.png)

Code recognition of CSS breaks after the first statement referencing a variable when inlined into an HTML Element. This affects things like suggestions and syntax-highlighting. (I am new to webdev, so terminology may not be correct)

In the example above and below it breaks after `{b}`

```svelte
<script>
    let b = 50;
    let r = 20;
</script>

<div class="box" style="--b: {b}; --r: {r}"></div>

<style>
    .box {
        height: 100px;
        width: 100px;
        background: rgb(var(--r), 200, var(--b));
    }
</style>
```

**Comment by tomblachut** [comment] 2022-03-23 12:25
Hi, duplicate of #80

**Closed by tomblachut** 2022-03-23 12:25 UTC
