### ISSUE TITLE
When using #await #then type information gets lost

### ISSUE THREAD

**Issue by redmagic** [tomblachut/svelte-intellij#225] opened 2021-06-11 12:48 UTC
In the template code, `#await` argument has the proper typing:

![image](https://user-images.githubusercontent.com/1224765/121688455-c22b8e80-cac3-11eb-8236-d46f74f4aca0.png)

But in the `#then` statement the type is gone:

![image](https://user-images.githubusercontent.com/1224765/121688623-f4d58700-cac3-11eb-9992-39a623111207.png)

**Comment by tomblachut** [comment] 2021-06-14 08:18
Closing as duplicate of #207

**Closed by tomblachut** 2021-06-14 08:18 UTC
Labels: area: types
