### ISSUE TITLE
Double quotes in dynamic property shows syntax error

### ISSUE THREAD

**Issue by rster2002** [tomblachut/svelte-intellij#247] opened 2021-08-23 19:42 UTC
Just installed WebStorm and the plugin so this might be a configuration issue. I'm also not really sure if this is the right place to create this issue so let me know if this is not the place to create this issue.

![image](https://user-images.githubusercontent.com/26026518/130508887-be34fb13-2110-4f45-8004-9ea9b78a33b6.png)
I expect to use double quotes within `{}` as this is syntax valid in svelte as you can see [here](https://svelte.dev/repl/da6ded8a24b34348936564ca38d958a0?version=3.42.2). 

Let me know you need anything else.

**Comment by tmarsik42** [comment] 2022-07-21 08:08
This is a bit old but I don't think it's a good idea. It might compile without error but it is so wrong to nest quotes of the same type. Even repl you posted is screaming at you (in colors) that it is wrong. Highlighters don't know where the parameter starts and ends.
<img width="429" alt="Snímek obrazovky 2022-07-21 v 10 07 25" src="https://user-images.githubusercontent.com/95856146/180163150-15f1b38c-56bd-4d79-be94-e1078afa8cb3.png">

**Comment by rster2002** [comment] 2022-07-22 21:49
I've since stopped doing this because it's not supported in this plugin, but from what I can remember the official svelte plugin for VS code does allow for this, but I would have to check.

**Comment by rster2002** [comment] 2022-07-22 22:23
After checking, it seems the [official svelte plugin](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) for VS code does allow this:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/26026518/180576112-40dbe56a-8433-4842-828a-98fbb02e0983.png">

**Comment by tomblachut** [comment] 2023-07-04 17:14
Duplicate of #194

**Closed by tomblachut** 2023-07-04 17:14 UTC
