### ISSUE TITLE
Import get placed in curly braces

### ISSUE THREAD

**Issue by Maggi64** [tomblachut/svelte-intellij#196] opened 2020-12-27 17:20 UTC
I encountered another bug. 

https://user-images.githubusercontent.com/20517052/103176203-11f8ff00-4870-11eb-9130-d5020df9b421.mp4

Best wishes 🎁

**Comment by tomblachut** [comment] 2020-12-28 14:17
Duplicate of #129

**Closed by tomblachut** 2020-12-28 14:17 UTC
